version: "3.8"
service:
 customer-service:
  build: 
   context: .
  dockerfile: Dockerfile
  container_name: docker-customer-service
 restart: always
 ports:
   - 8081:8081
 networks:
      bank_network:
        aliases:
          - app_subnet
networks:
  bank_network:
    name: app_subnet
    external: true
 
    